// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ItNpKMCw0zZEsSoomPt0erCzMOvXIV8',
    appId: '1:1029884992968:web:d64ea40267c88a6ec734fd',
    messagingSenderId: '1029884992968',
    projectId: 'muhafiz-ef76e',
    authDomain: 'muhafiz-ef76e.firebaseapp.com',
    storageBucket: 'muhafiz-ef76e.firebasestorage.app',
    measurementId: 'G-D70V1V17JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wtrhwfbQM6bVnPJMirCSWs7L8oXLopI',
    appId: '1:1029884992968:android:c48928dd3c271e8dc734fd',
    messagingSenderId: '1029884992968',
    projectId: 'muhafiz-ef76e',
    storageBucket: 'muhafiz-ef76e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKLhyI_HT3KvpNQiwC9ZxBonwJo89NPA',
    appId: '1:1029884992968:ios:c99fff2c89077271c734fd',
    messagingSenderId: '1029884992968',
    projectId: 'muhafiz-ef76e',
    storageBucket: 'muhafiz-ef76e.firebasestorage.app',
    iosClientId: '1029884992968-877bkg29h6nm6f0me64c90lvja1hfmu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.muhafiz1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKLhyI_HT3KvpNQiwC9ZxBonwJo89NPA',
    appId: '1:1029884992968:ios:c99fff2c89077271c734fd',
    messagingSenderId: '1029884992968',
    projectId: 'muhafiz-ef76e',
    storageBucket: 'muhafiz-ef76e.firebasestorage.app',
    iosClientId: '1029884992968-877bkg29h6nm6f0me64c90lvja1hfmu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.muhafiz1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8ItNpKMCw0zZEsSoomPt0erCzMOvXIV8',
    appId: '1:1029884992968:web:8cb1c51fa8359ae9c734fd',
    messagingSenderId: '1029884992968',
    projectId: 'muhafiz-ef76e',
    authDomain: 'muhafiz-ef76e.firebaseapp.com',
    storageBucket: 'muhafiz-ef76e.firebasestorage.app',
    measurementId: 'G-H75RVHLLY6',
  );

}